"""Make a model directory loadable from HuggingFace Hub via ``trust_remote_code``.

This implements the **pip-install distribution** path: the consumer needs
``alloy`` installed in their Python env, and the HF Hub repo just contains a
thin shim ``modeling_alloy.py`` that re-exports ``AlloyConfig`` /
``AlloyForCausalLM`` from the installed package, plus an ``auto_map`` field
in ``config.json`` so HF's dynamic-class loader resolves the names.

Why this path
-------------
- The shim is one line, version-coupled to whatever ``alloy`` the consumer
  has installed.
- alloy is the canonical source of truth for the model definition; bug fixes
  / refactors propagate by ``pip install --upgrade alloy``, not by re-uploading
  every checkpoint.
- HF's ``trust_remote_code`` loader has limitations with multi-file remote
  packages (its relative-import scanner doesn't recurse, doesn't handle
  nested package dirs reliably across versions). A thin shim sidesteps all
  of that by deferring to a normal ``pip install``-resolved import.

The trade-off: a checkpoint published today is loadable only from a Python
env where ``alloy`` is installed and compatible. Once a model definition is
stable that's a non-issue; if HF's API drifts the responsibility is on alloy
to follow, not on individual checkpoints.

Usage as a function::

    from alloy.tools.export_for_hub import export_for_hub
    model.save_pretrained("my_alloy_model")
    tokenizer.save_pretrained("my_alloy_model")
    export_for_hub("my_alloy_model")
    # -> upload my_alloy_model/ to HF Hub

Consumer side::

    pip install alloy
    AutoModelForCausalLM.from_pretrained("user/my_alloy_model", trust_remote_code=True)

Usage as a CLI::

    python -m alloy.tools.export_for_hub my_alloy_model
"""
from __future__ import annotations

import argparse
from pathlib import Path
from textwrap import dedent

# Filename HF auto_map points at. Single source of truth; if you change this,
# update both the file write and the auto_map values below.
_SHIM_FILENAME = "modeling_alloy.py"

_SHIM_CONTENT = dedent('''\
    """Thin shim re-exporting alloy classes for HF Hub ``trust_remote_code`` loading.

    Generated by ``alloy.tools.export_for_hub``. Consumers must have the
    ``alloy`` package installed (``pip install alloy``); HF's auto-class
    loader instantiates ``AlloyConfig`` / ``AlloyForCausalLM`` referenced by
    ``config.json``'s ``auto_map``, this file just resolves those names from
    the installed package.
    """
    from alloy import AlloyConfig, AlloyForCausalLM  # noqa: F401
''')

_AUTO_MAP = {
    "AutoConfig": f"{_SHIM_FILENAME[:-3]}.AlloyConfig",
    "AutoModelForCausalLM": f"{_SHIM_FILENAME[:-3]}.AlloyForCausalLM",
}


def export_for_hub(target_dir: str | Path) -> Path:
    """Make ``target_dir`` HF-Hub-loadable via ``trust_remote_code``.

    Writes ``modeling_alloy.py`` (a one-line shim) and injects ``auto_map``
    into the existing ``config.json``. Caller is responsible for having
    already done ``model.save_pretrained(target_dir)`` (and tokenizer save,
    if applicable).

    Parameters
    ----------
    target_dir : path-like
        Directory containing ``config.json`` and weights. Modified in place.

    Returns
    -------
    Path
        ``target_dir`` for chaining.

    Raises
    ------
    FileNotFoundError
        If ``target_dir`` does not exist or does not yet contain ``config.json``.
    """
    from alloy.configuration_alloy import AlloyConfig

    target_dir = Path(target_dir)
    if not target_dir.is_dir():
        raise FileNotFoundError(f"target_dir does not exist: {target_dir}")

    cfg_path = target_dir / "config.json"
    if not cfg_path.is_file():
        raise FileNotFoundError(
            f"{cfg_path} not found. Run model.save_pretrained({str(target_dir)!r}) "
            f"before exporting."
        )

    # Write the shim. Overwrite if it already exists — running export_for_hub
    # twice on the same directory should be idempotent.
    (target_dir / _SHIM_FILENAME).write_text(_SHIM_CONTENT, encoding="utf-8")

    # Inject auto_map. AlloyConfig.save_pretrained re-emits with the
    # group-based JSON layout (blank lines between sections) so the
    # human-readable formatting survives the round-trip.
    cfg = AlloyConfig.from_pretrained(target_dir)
    cfg.auto_map = dict(_AUTO_MAP)
    cfg.save_pretrained(target_dir)

    return target_dir


def _main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "target_dir",
        help="Directory containing config.json + weights (typically the "
             "output of model.save_pretrained()). Modified in place.",
    )
    args = parser.parse_args()
    out = export_for_hub(args.target_dir)
    print(f"Exported alloy shim into {out}")
    print(f"  Wrote: {_SHIM_FILENAME}")
    print(f"  auto_map injected:")
    for k, v in _AUTO_MAP.items():
        print(f"    {k} -> {v}")
    print("Consumer needs `pip install alloy` for trust_remote_code to resolve.")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
